version: '3.3'

services:
  listings:
    build:
      context: ./services/listings
      dockerfile: Dockerfile-dev
    volumes:
      - './services/listings:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
    
